#application configuration
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/streaming-app?server
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /public/**
server:
  port: 8080

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    expiration-time: 3600000