#application configuration
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/streaming-app?server
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /public/**